django/blog/urls.py
from django.conf.urls import patterns, url
from blog import views

urlpatterns = patterns('',

url(r'^(\d*)$', views.index, name='index'),

url(r'^view/(?P<slug>[^\.]+)', 
    views.view_post, 
    name='view_blog_post'),
    
url(r'^category/(?P<slug>[^\.]+)', 
    views.view_category, 
    name='view_blog_category'),
)

django/mw/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.http import HttpResponseRedirect
from django.contrib.flatpages import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^projects/', include('projects.urls', namespace="projects")),
    url(r'^sefik/', include(admin.site.urls)),
#    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^media/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^spirit/', include('spirit.urls')),
)

urlpatterns += [
    url(r'^about/$', views.flatpage, {'url': '/about/'}, name='about'),
    url(r'^/$', views.flatpage, {'url': '/'}, name='home'),
    ]

django/templates/base.html
{% load i18n staticfiles %}
{% load categ_tags %}
<!DOCTYPE HTML>
<!--
    Striped 2.5 by HTML5 Up!
    html5up.net | @n33co
    Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
    -->
<html>
{% block nacten %}
    <head>
        {% block head %}
        {% endblock %}
        <title>{% block head_title %}{% endblock %}</title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
        <meta name="description" content=""/>
        <meta name="keywords" content=""/>
        <meta name="google-site-verification" content="LNMVFDTJEiILChBcN08v8_lNQ7yC0OvDqvHRmNC8fYw" />
        <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400italic,700|Open+Sans+Condensed:300,700"
              rel="stylesheet"/>
        <!-- Maly hack k tomu, aby v javascriptu (skel.min.js) fungoval "static_url" -->
        <script language="javascript">var STATIC_URL = "{{ STATIC_URL }}";</script>
        <script src="{{ STATIC_URL }}js/jquery.min.js"></script>
        <script src="{{ STATIC_URL }}js/skel.min.js"></script>
        <script type="text/javascript"
          src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
        </script>
        <script src="{{ STATIC_URL }}js/skel-panels.min.js"></script>
        <script src="{{ STATIC_URL }}js/init.js"></script>
        <noscript>
            <link rel="stylesheet" href="{{ STATIC_URL }}css/skel-noscript.css"/>
            <link rel="stylesheet" href="{{ STATIC_URL }}css/style.css"/>
            <link rel="stylesheet" href="{{ STATIC_URL }}css/style-desktop.css"/>
            <link rel="stylesheet" href="{{ STATIC_URL }}css/style-wide.css"/>
        </noscript>
        <!--[if lte IE 9]>
        <link rel="stylesheet" href="css/ie9.css" />
        <![endif]-->
        <!--[if lte IE 8]><script src="js/html5shiv.js"></script>
        <link rel="stylesheet" href="css/ie8.css" />
        <![endif]-->
        <!--[if lte IE 7]>
        <link rel="stylesheet" href="css/ie7.css" />
        <![endif]-->
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-45598913-1', 'auto');
          ga('require', 'displayfeatures');
          ga('require', 'linkid', 'linkid.js');
          ga('send', 'pageview');

        </script>
        {% block disqus_count %}
        {% endblock %}
    </head>
{% endblock %}
<!--
    Note: Set the body element's class to "left-sidebar" to position the sidebar on the left.
    Set it to "right-sidebar" to, you guessed it, position it on the right.
    -->
<body class="left-sidebar">
<!-- Wrapper -->
<div id="wrapper">
    <!-- Content -->
    <div id="content">
        <div id="content-inner">
            {% block content %}
            {% endblock %}
        </div>
    </div>
    <!-- Sidebar -->
    <div id="sidebar">
        <!-- Logo -->
        <div id="logo">
            <h1>Daniel H.</h1>
        </div>
        <!-- Nav -->
        <nav id="nav">
            <ul>
                <li {% block ci1 %} {% endblock %}><a href="/blog/">Blog</a></li>
                <li {% block ci2 %} {% endblock %}><a href="/projects/">Projects</a></li>
                <li {% block ci3 %} {% endblock %}><a href="/about/">About me</a></li>
            </ul>
        </nav>

        <!-- Search CO PRIDAT GOOGLE CUSTOM SEARCH?
        <section class="is-search">
            <form method="post" action="#">
                <input type="text" class="text" name="search" placeholder="Search"/>
            </form>
        </section>
        -->

        <!-- Recent Posts -->
        <section class="is-recent-posts">
            <header>
                <h2>Latest articles</h2>
            </header>
            <ul>
                {% for post in L_POSTS %}
                    <li><a href="{% url 'blog:view_blog_post' post.slug %}">{{ post.title }}</a></li>
                {% endfor %}
            </ul>
        </section>

        <section class="is-recent-comments">
            {% block cates %}
                <header>
                    <h2>Categories</h2>
                </header>
                <ul>
                    {% for category in ALL_CATEGS %}
                        <!-- Tohle byl fail pokus - ale naucil jsem se, jak delat custom tagy -->
                        <!-- momentalne vraci vsechny blogy z dane categorie - ovsem jako objekty a tedy se renderuji jako stringy... -->
                        <!--  <li><a href="{% get_pub category.title  %}">{{ category.title }}</a></li> -->
                        <li><a href="{% url 'blog:view_blog_category' category.slug %}">{{ category.title }}</a></li>
                    {% endfor %}
                </ul>
            {% endblock %}
        </section>

        <!-- Copyright -->
        <div id="copyright">
            <p>
                &copy; {% now "Y" %} Daniel Hnyk<br/>
                Design: <a href="http://html5up.net/">HTML5 UP</a>
            </p>
        </div>
    </div>
</div>
</body>
</html>