django/mw/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.http import HttpResponseRedirect
from django.contrib.flatpages import views

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^projects/', include('projects.urls', namespace="projects")),
    url(r'^sefik/', include(admin.site.urls)),
#    url(r'^summernote/', include('django_summernote.urls')),
    url(r'^media/(?P<path>.*)$',
        'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}),
    url(r'^spirit/', include('spirit.urls')),
)

urlpatterns += [
    url(r'^about/$', views.flatpage, {'url': '/about/'}, name='about'),
    url(r'^/$', views.flatpage, {'url': '/'}, name='home'),
    ]

django/projects/urls.py
from django.conf.urls import patterns, url
from projects import views

urlpatterns = patterns('',

url(r'^(\d*)$', views.index, name='index'),

url(r'^view/(?P<slug>[^\.]+)', 
    views.view_project,
    name='view_project'),

)

django/projects/models.py
from django.db import models
from easy_thumbnails.fields import ThumbnailerImageField
from markupfield.fields import MarkupField

def get_name_file(instance, filename):
    strge = 'pictures/projects/' + str(instance.slug) + filename[-4:]
    return(strge)

class Project(models.Model):
    title = models.CharField(max_length=100, unique=True)
    description = MarkupField(markup_type="ReST")
    slug = models.SlugField(max_length=100, unique=True)
#    body = models.TextField()
    start = models.DateField(db_index=True, auto_now_add=True)
    last_mod = models.DateField(auto_now=True)
    body_marked = MarkupField(markup_type="ReST")
    end = models.DateField(db_index=True, auto_now_add=True)
    pclass = models.ForeignKey('projects.PClass')
    publish = models.BooleanField(default=False, verbose_name="Should I publish it?")
    title_pic = ThumbnailerImageField(
        upload_to=get_name_file,
        null=True, blank=True,
        verbose_name="Titulní foto")

class PClass(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    pclass_pic = ThumbnailerImageField(
        upload_to=get_name_file,
        verbose_name="Foto kategorie")

    def __str__(self):
        return self.title

django/projects/views.py
from django.shortcuts import render_to_response, get_object_or_404, render
from django.http import HttpResponse
from projects.models import Project, PClass


def index(request, offset):
    # Mozna by chtelo zvlast passed a active
    projects = Project.objects.filter(publish=True)
    pclasses = PClass.objects.all()

    context = {
        'projects': projects,
        'pclasses' : pclasses,
    }
    return render(request, 'projects_index.html', context)

def view_project(request, slug):
    context = { 'project': get_object_or_404(Project, slug=slug),
                }
    return render(request, 'view_project.html', context)

django/projects/templates/projects_index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block head_title %}{{ 'Projects' }}{% endblock %}
{% block ci2 %} class="current_page_item" {% endblock %}
{% block content %}

    {% for pclass in pclasses %}
        <h1 class="outer">{{ pclass }}</h1>
        <img src={{pclass.pclass_pic|thumbnail_url:"small" }} />
        <ul>
        {% for project in projects %}
            {% if project.pclass == pclass %}
            <li>
                <h2><a href="{% url 'projects:view_project' project.slug %}">{{ project.title }}</a></h2>
            </li>
            {% endif %}
            {% endfor %}
        </ul>
        <hr>
    {% endfor %}

{% endblock %}

django/projects/templates/view_project.html
{% extends 'base.html' %}
{% block ci2 %} class="current_page_item" {% endblock %}
{% block head_title %}{{ project.title }}{% endblock %}
{% block disqus_count %}
<script type="text/javascript">
/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
var disqus_shortname = 'dnhnk'; // required: replace example with your forum shortname

/* * * DON'T EDIT BELOW THIS LINE * * */
(function () {
    var s = document.createElement('script'); s.async = true;
    s.type = 'text/javascript';
    s.src = '//' + disqus_shortname + '.disqus.com/count.js';
    (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>
{% endblock  %}
{% block content %}

<article class="is-post is-post-excerpt">
    <header>
        <h1 class="outer">{{ project.title }}</h1>
        </header>

    <div class="info">
        <span class="date"><span class="day">{{ project.start |date:"j" }}. </span><span class="month">{{ project.start  |date:"F"|slice:":3" }}<span>{{ project.start |date:"F"|slice:"3:" }}</span></span> <span class="year">{{ project.start |date:"Y" }}</span></span>
        <ul class="stats">
            <li><a href="#" class="fa fa-comment"><a href="{% url 'projects:view_project' project.slug  %}#disqus_thread">0</a></a></li>
        </ul>

    </div>
    <p>

        {{ project.body_marked|safe }}
    </p>
    <hr>
    <table>
    <tr>
        <th><p align="left">Category: {{ project.pclass }}</p></th>
        <th><p align="right">Last <a class="nostyling" href="{% url 'admin:projects_project_change' project.id %}">modified</a>: {{ project.last_mod }}</p></th>
    </tr>
    </table>
    
   
    <!-- START DISQUS -->
    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'dnhnk'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
    <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
<!-- END DISQUS -->
    </div>

</article>


{% endblock %}